export const ProductsTypes = {
	PRODUCTS_REQUEST: 'PRODUCTS_REQUEST',
	PRODUCTS_SUCCESS: 'PRODUCTS_SUCCESS',
	PRODUCTS_FAIL: 'PRODUCTS_FAIL',
	PRODUCT_REQUEST: 'PRODUCT_REQUEST',
	PRODUCT_SUCCESS: 'PRODUCT_SUCCESS',
	PRODUCT_FAIL: 'PRODUCT_FAIL'
};
